version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./data/storage:/data/db
    networks:
      - default

  todo:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./data/files:/files
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - default
